version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: surfschool-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-clasedesurf.com}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - surfschool-network
    restart: unless-stopped

  # Backend API
  backend:
    image: chambadigital/surfschool-backend:latest
    container_name: surfschool-backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-clasedesurf.com}"
      JWT_SECRET: "${JWT_SECRET:-change-this-in-production}"
      PORT: 4000
      NODE_ENV: "production"
      FRONTEND_URL: "${FRONTEND_URL:-http://localhost:3000}"
    depends_on:
      - postgres
    networks:
      - surfschool-network
    restart: unless-stopped

  # Frontend (Next.js)
  frontend:
    image: chambadigital/surfschool-frontend:latest
    container_name: surfschool-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-http://localhost:4000}"
      NEXTAUTH_URL: "${NEXTAUTH_URL:-http://localhost:3000}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET:-change-this-in-production}"
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-clasedesurf.com}"
    depends_on:
      - backend
      - postgres
    networks:
      - surfschool-network
    restart: unless-stopped

  # Redis (opcional)
  redis:
    image: redis:7-alpine
    container_name: surfschool-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - surfschool-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  surfschool-network:
    driver: bridge
